apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: preload
  namespace: preload
spec:
  selector:
    matchLabels:
      name: preload
  template:
    metadata:
      labels:
        name: preload
    spec:
      initContainers:
      {{range $idx, $image := .Images}}
      - name: preload-{{$idx}}
        image: docker
        command: ["ctr", "pull", "{{$image}}"]
        volumeMounts:
        - name: docker
          mountPath: /var/run/containerd/containderd.sock
      {{end}}
      volumes:
      - name: docker
        hostPath:
          path: /var/run
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
